runtimeverification/plutus-core-semantics

uplc-syntax.md
The top of the concrete syntax module started with a list of builtin
functions. Although builtin functions are important part of the
language, this is not as important as the actual syntax. Move the more
interesting syntax declarations above the builtin functions. Also,
replace comments that take up entire lines with markdown.
There is no functional change intended with this change.
=> Move syntax declarations and use MarkDown

tests/failing, tests/simple/ifThenElse-no-force.uplc, uplc-polymorphic-builtins.md
The draft semantics of UPLC of Jan 27th requires every polymorphic builtin to be composed with `force` when applied. This PR adds this.
=> Added force to ifThenElse builtin.

uplc-configuration.md, uplc-syntax.md
This pull request contains several small changes that cleans up the flat parser syntax.
=> Move definitions from syntax to configuration module 

Makefile, tests/simple/fstPairOfPairAndList.uplc, tests/simple/fstPairOfPairAndList.uplc.krun.expected, tests/simple/pairOfPairAndList.uplc, tests/simple/sndPairOfPairAndList.uplc, tests/simple/sndPairOfPairAndList.uplc.krun.expected, uplc-polymorphic-builtins.md, uplc-syntax.md
Builtins ' fstPair'  and 'sndPair'  are polymorphic builtins that are applied to terms such as `(con pair (integer)(bytestring) (0, #AF))`. Their denotation is the first and second projections of a pair.
=> Add support for fstPair and sndPair. Add one example for each builtin.

tests/simple/trace.uplc, tests/simple/trace.uplc.expected, tests/simple/trace.uplc.krun.expected, uplc-polymorphic-builtins.md, uplc-syntax.md
This PR is essentially #121 but with a different Makefile where the command line for test does not use `krun` `--output program` but rather a sed command that removes all `.*List` constants, denoting empty lists. As shown in PR #121, `--output program` raises an exception for `trace.uplc` UPLC program.
=> Add trace builtin.

bitstream.md, tests/flat/false.flat.expected, tests/flat/true.flat.expected, tests/flat/unitval.flat.expected, uplc-configuration.md, uplc-flat-parser.md
The previous implementation used the `Bytes` sort to implement a very limited prototype of the flat parser. This pull request implements uses a new BitStream sort to facilitate parsing the flat format. This is an initial attempt that parses the existing flat tests properly. More to come later.
=> Update Flat Parser Using BitStream Sort

tests/failing, tests/uplc-examples/NatRoundTrip.uplc.expected, tests/uplc-examples/NatRoundTrip.uplc.krun.expected, tests/uplc-examples/ScottListSum.uplc.expected, tests/uplc-examples/ScottListSum.uplc.krun.expected, uplc-environment.md, uplc-semantics.md, uplc-syntax.md
This pull request fixes the syntax for uplc variables. Uplc variables allow a `'` which is disallowed by the `Id` sort found in `domains.md`. Fix the identifier syntax so it matches the spec and remove a few tests from `tests/failing`.
=> Fix variable identifier syntax

Jenkinsfile, Makefile, tests/flat/false.flat.expected, tests/flat/false.flat.krun.expected, tests/flat/true.flat.expected, tests/flat/true.flat.krun.expected, tests/flat/unitval.flat.expected, tests/flat/unitval.flat.krun.expected
This pull request contains changes that updates the flat format tests and expected outputs. `make test-flat` now compares output between `uplc` and `kplc` (similar to `test-simple`).
=> update flat format tests

tests/failing, uplc-bytestring-builtins.md, uplc-configuration.md, uplc-crypto-builtins.md, uplc-integer-builtins.md, uplc-polymorphic-builtins.md, uplc-semantics.md, uplc-string-builtins.md
Even though this is a large PR, in terms of the number of modified lines of code, the modification is simple with respect to #135. Builtin evaluation relies on decrementing the number of arguments it expects in order to actually call the proper builtin function that does the job. This decrementing was being computed all the way down to 0. It led however to states such as `V ~> [ < builtin bn L 0 > _]`, where `V` is a Value, `bn` is a builtin name, and `L` is a (semantic) list with the arguments of `bn`. There are no such rule to further reduce such states. What needs to be done is to let evaluation go down to 1 and then directly call the function that does the job, where states as above are not reachable. 
So this PR essentially changes builtin evaluation to 
```
rule <k> V:Value ~> [ < …
```
=> Fixed a bug on builtin evaluation.

uplc-flat-parser.md
There was a bug in kompile that did not allow macro labels on hooked
sorts. This has been resolved so macro labels are now allowed on
productions of hooked sorts.
=> Place macro symbols on productions

.gitignore, Jenkinsfile, Makefile, kplc, unit-tests/flat-unit-test.md, unit-tests/verification.k
Components such as the flat parser requires programming many functions
before a realistic program can be parsed as input. To facilitate
development, enable unit testing and add a new target
`make run-unit-tests` in order to execute the unit tests. Each test is
written as a claim inside of a md file in the unit-tests directory.
=> Enable K unit testing

tests/simple/subtractInteger-non-iter.uplc, tests/simple/subtractInteger-non-iter.uplc.expected, tests/simple/subtractInteger-non-iter.uplc.krun.expected, uplc-semantics.md
Applications of the form `[M N1 N2 ... Nn]` are translated into (the denotation of) `[... [M N1] N2] ...] Nn]`.
However, the arguments were being pushed in the wrong order. This PR fixes it.
=> Fix non-iterative application

uplc-flat-parser.md
This pull request refactors the flat parser by extracting a function to parse terms and removes the need to pass the UPLC program version from all of the recursive function rewriting rules. Additionally, this pull request removes several magic numbers to improve readability.
=> Flat parser: extract function to Parse a Term

uplc-configuration.md, uplc-environment.md, uplc-semantics.md
This PR adds the notion of a _heap_ to KPlutus aiming at reducing duplications on the term at the K cell.
Each value in UPLC has its own environment. That generates a lot of copies of bindings on a given term. Instead of repeating the terms we simply add a reference to it in the heap.
There has been a change in the behavior regarding files in `tests/benchmark-validation-examples/`: files that filled up `result.kore` now reach a stuck state. But this does still require further analysis and experimentation for instance by truely sharing heap elements instead of just referencing potentially replicated terms.
Developed by: @SchmErik
=> change function application to use heaps

tests/failing, uplc-semantics.md, uplc-syntax.md
* The semantics for non-iteractive application was incorrect. It would
be necessary to distribute the term being applied to its arguments
and that would depend on the arity of the function. Since this is
not specified in the CEK machine for UPLC and is not (fully, at
least) supported by `uplc`, this commit removes it from the
semantics. Only applications of the form `[Term Term]` are allowed.
* Test `tests/uplc-examples/factorial2.uplc` (that calculates the
factorial of 1000) segfaults. It seems that the large heap is the
source of the problem. It is not really related to the main subject but it broke my test. So I decided to add it to tests/failing
=> Remove non-iteractive application

Makefile, README.md
These targets generate coverage information of K rewrite rules. The
following sequence of commands generates a `.build/coverage.xml` file
that contains information about the rules that have been exercised
during the execution of `make conformance-test`.
```
make build-coverage
make conformance-test
make coverage
```
The information found in the xml file can help us determine which test
cases need to be added to ensure that our test suite exercises all rules.
=> Makefile: add build-coverage and coverage targets

tests/failing, tests/simple/addInteger-non-interactive.uplc, tests/simple/addInteger-non-interactive.uplc.expected, tests/simple/subtractInteger-non-interactive.uplc, tests/simple/subtractInteger-non-interactive.uplc.expected, uplc-semantics.md, uplc-syntax.md
This PR returns support for non-iterative application. A program such as
```
(program 0.0.0 [(builtin subtractInteger) (con integer 1) (con integer 4)])
```
is equivalently to
```
(program 0.0.0 [ [(builtin subtractInteger) (con integer 1) ] (con integer 4)])
```
However,
```
(program 0.0.0 [(builtin subtractInteger) (con integer 1) (con integer 4) (con integer 0)])
```
is neither supported by `kplc` nor `uplc`.
=> Add support for non-interactive application

simple-proofs/simple-symbolic.md, uplc-discharge.md, uplc-semantics.md, uplc-syntax.md
The use of syntactic lists results in stuck states on #appAux. Replacing
the use with its syntactic equivalent somehow makes some claims evaluate
further due to a possible bug in the haskell backend.
=> Drop syntactic list

tests/textual/new-syntax/tailList.uplc.expected, tests/textual/new-syntax/tailList2.uplc.expected, uplc-polymorphic-builtins.md
The evaluation rule for `tailList` was missing the `list` type constant.
This change adds the list type constant to the result of this
evaluation.
=> Fix tailList semantics

simple-proofs/simple-symbolic.md, simple-proofs/verification.k, uplc-environment.md, uplc-hash.md, uplc-semantics.md
This PR adds a simple claim for identity function applied to the constant `(con integer 1)`. In order prove this claim, several modifications to existing functions and simplification rules were added to prove the claim.
Closes: https://github.com/runtimeverification/plutus-core-semantics/issues/220
=> Prove simple identity claim with concrete inputs

tests/textual/new-syntax/maxList.uplc, tests/textual/new-syntax/maxList.uplc.expected, tests/textual/new-syntax/maxListTailRec.uplc, tests/textual/new-syntax/maxListTailRec.uplc.expected
fixes: #222 
Implemented are two variants, one is recursive, and the other is tail recursive.
The function makes two assumptions about the list that gets passed in to it:
- The list will be non-empty
- Each number in the list will be greater than or equal to 0
=> Maximum integer from list function

tests/textual/new-syntax/listSum.uplc, tests/textual/new-syntax/listSum.uplc.expected
This test is an implementation of a function that adds all list
elements. It's possible to implement this function using several
different approaches such as y-combinator, tail recursion, and etc.
The y-combinator was used to impelement this function but it's possible
that tail recursion could be more efficient for proofs...
Closes: https://github.com/runtimeverification/plutus-core-semantics/issues/223
=> Add list sum test and expected output

.gitignore, simple-proofs/simple-symbolic.md, uplc-bytestring-builtins.md, uplc-crypto-builtins.md, uplc-data-builtins.md, uplc-integer-builtins.md, uplc-polymorphic-builtins.md, uplc-semantics.md, uplc-string-builtins.md
According to the CEK machine defined in the Plutus spec, the state
indicating the return phase does not contain an environment. By leaving
this cell alone, it's possible for the steps in the return phase to
maintain unneeded elements in `<Env>`. While this has no implications for
`kplc run`, this will make it difficult to write general claims. This
change rewrites the `<Env>` cell to `.Map` when the computation
transitions between the compute phase to the return phase for constants,
variables, lambda, delay, and builtin.
=> Clean env on return phase

tests/failing, tests/textual/simple/false-var.uplc, tests/textual/simple/true-var.uplc
- `uplc` allows for variables named `True` and `False`. This commit
adds two tests, one for each case.
- It also adds two new entries to `tests/failing` until we rewrite the
grammar to support that.
=> Add tests for True and False as variable names

uplc-semantics.md
Memoization of `#FV` leads to performance improvements in symbolic execution.
=> Memoization of `#FV`

Makefile, kplc
Here's a quick little PR that adjusts `kplc kompile` to only pass llvm specific arguments when the backend to kompile for is llvm, and keeps debug/release related options only in their own respective build profiles.
=> Build system refactors

IOG-contracts/native-tokens/native-tokens/native-tokens.cabal, IOG-contracts/stablecoin/stablecoin/stablecoin.cabal
- Compilation options
```
-fplugin-opt PlutusTx.Plugin:no-simplifier-inline
-fplugin-opt PlutusTx.Plugin:no-simplifier-beta
```
should be under `ghc-options` for the library targets in `.cabal` files.
=> Fix compilation options in `native-tokens.cabal` and `stablecoin.cabal`

Makefile
- The `gen-bison-parser` option generates a more efficient parser
based on `bison`. To add this option we need to make sure our
grammar is LR(1), which seems to be the case, and that bison's
version is greater or equal to 3.7.4.
- This commit adds the `gen-bison-parser` option to KOMPILE_OPTS
should bison's version fulfill the version requirement above.
=> Add `gen-bison-parser` to KOMPILE_OPTS

simple-proofs/verification.md, uplc-integer-builtins.md
The castToInt trick will no longer be needed once https://github.com/runtimeverification/haskell-backend/pull/3202 is merged into the Haskell backend.
The `allInts(XS)` predicate is changed so that the associated reasoning happens at the ML-level.
=> Removing castToInt

uplc-semantics.md
The global environment is no longer used for concrete execution.
=> Removing global environment from concrete execution

tests/textual/simple/discharge-delay-app.uplc, tests/textual/simple/discharge-delay-app.uplc.expected, tests/textual/simple/discharge-delay-nested-app.uplc, tests/textual/simple/discharge-delay-nested-app.uplc.expected, uplc-discharge.md
Discharge function for nested applications and iterative applications
resulted in stuck terms. This change adds additional rules to correctly
terminate discharge applied to nested applications.
=> Fix discharge for applications and add tests

uplc-discharge.md
- Fix discharge for lambdas. A lambda value `< lam X:UplcId T:Term RHO:Map >` should discharge `RHO[X <- undef]` in `T` if `X` in `RHO` or simply `RHO` otherwise.
=> Fix discharge function on lambdas.

Dockerfile, Makefile
This PR fixes the bison flag check and upates K image from focal to Jammy. By doing so, we can use a newer version of bison for kompile's `--gen-bison-parser` option.
=> Fix bison flag and update k image

README.md
Since the KLLVM python bindings have been added, the Python development headers are a requirement to build K. This PR adds them to the suggested Ubuntu packages.
Additionally, we no longer recommend using LLVM 10 in package lists as it's not present on Ubuntu Jammy. This PR bumps the recommended version to 12.
The upstream K PR that these changes are derived from is: https://github.com/runtimeverification/k/pull/2891.
=> README: update Ubuntu packages

.github/workflows/test-pr.yml
- Changes `make test-prove` action on CI to consider  `KORE_EXEC_OPTS="--log-level error"` as in the current version of
the Haskell backend `trivial-policies.md` is generating a ~100MB log message.
=> Log level to error on CI while proving simple

flake.nix
nix built `kplc --version` would previously return nothing.
=> [nix] Add rev tag information to `kplc --version`
